var searchData=
[
  ['wascanceled_59979',['wasCanceled',['http://doc.qt.io/qt-5/qprogressdialog.html#wasCanceled-prop',1,'QProgressDialog']]],
  ['watchedservices_59980',['watchedServices',['http://doc.qt.io/qt-5/qdbusservicewatcher.html#watchedServices-prop',1,'QDBusServiceWatcher']]],
  ['watchmode_59981',['watchMode',['http://doc.qt.io/qt-5/qdbusservicewatcher.html#watchMode-prop',1,'QDBusServiceWatcher']]],
  ['whatsthis_59982',['whatsThis',['http://doc.qt.io/qt-5/qaction.html#whatsThis-prop',1,'QAction::whatsThis()'],['http://doc.qt.io/qt-5/qshortcut.html#whatsThis-prop',1,'QShortcut::whatsThis()'],['http://doc.qt.io/qt-5/qwidget.html#whatsThis-prop',1,'QWidget::whatsThis()']]],
  ['wheelscrolllines_59983',['wheelScrollLines',['http://doc.qt.io/qt-5/qstylehints.html#wheelScrollLines-prop',1,'QStyleHints::wheelScrollLines()'],['http://doc.qt.io/qt-5/qapplication.html#wheelScrollLines-prop',1,'QApplication::wheelScrollLines()']]],
  ['widgetresizable_59984',['widgetResizable',['http://doc.qt.io/qt-5/qscrollarea.html#widgetResizable-prop',1,'QScrollArea']]],
  ['width_59985',['width',['http://doc.qt.io/qt-5/qwindow.html#width-prop',1,'QWindow::width()'],['http://doc.qt.io/qt-5/qwidget.html#width-prop',1,'QWidget::width()']]],
  ['windowfilepath_59986',['windowFilePath',['http://doc.qt.io/qt-5/qwidget.html#windowFilePath-prop',1,'QWidget']]],
  ['windowflags_59987',['windowFlags',['http://doc.qt.io/qt-5/qgraphicswidget.html#windowFlags-prop',1,'QGraphicsWidget::windowFlags()'],['http://doc.qt.io/qt-5/qwidget.html#windowFlags-prop',1,'QWidget::windowFlags()']]],
  ['windowicon_59988',['windowIcon',['http://doc.qt.io/qt-5/qguiapplication.html#windowIcon-prop',1,'QGuiApplication::windowIcon()'],['http://doc.qt.io/qt-5/qapplication.html#windowIcon-prop',1,'QApplication::windowIcon()'],['http://doc.qt.io/qt-5/qwidget.html#windowIcon-prop',1,'QWidget::windowIcon()']]],
  ['windowicontext_59989',['windowIconText',['http://doc.qt.io/qt-5/qwidget-obsolete.html#windowIconText-prop',1,'QWidget']]],
  ['windowmodality_59990',['windowModality',['http://doc.qt.io/qt-5/qwidget.html#windowModality-prop',1,'QWidget']]],
  ['windowmodified_59991',['windowModified',['http://doc.qt.io/qt-5/qwidget.html#windowModified-prop',1,'QWidget']]],
  ['windowopacity_59992',['windowOpacity',['http://doc.qt.io/qt-5/qwidget.html#windowOpacity-prop',1,'QWidget']]],
  ['windowtitle_59993',['windowTitle',['http://doc.qt.io/qt-5/qdockwidget.html#windowTitle-prop',1,'QDockWidget::windowTitle()'],['http://doc.qt.io/qt-5/qgraphicswidget.html#windowTitle-prop',1,'QGraphicsWidget::windowTitle()'],['http://doc.qt.io/qt-5/qwidget.html#windowTitle-prop',1,'QWidget::windowTitle()']]],
  ['wizardstyle_59994',['wizardStyle',['http://doc.qt.io/qt-5/qwizard.html#wizardStyle-prop',1,'QWizard']]],
  ['wordwrap_59995',['wordWrap',['http://doc.qt.io/qt-5/qlistview.html#wordWrap-prop',1,'QListView::wordWrap()'],['http://doc.qt.io/qt-5/qtreeview.html#wordWrap-prop',1,'QTreeView::wordWrap()'],['http://doc.qt.io/qt-5/qtableview.html#wordWrap-prop',1,'QTableView::wordWrap()'],['http://doc.qt.io/qt-5/qlabel.html#wordWrap-prop',1,'QLabel::wordWrap()']]],
  ['wordwrapmode_59996',['wordWrapMode',['http://doc.qt.io/qt-5/qplaintextedit.html#wordWrapMode-prop',1,'QPlainTextEdit::wordWrapMode()'],['http://doc.qt.io/qt-5/qtextedit.html#wordWrapMode-prop',1,'QTextEdit::wordWrapMode()']]],
  ['wraparound_59997',['wrapAround',['http://doc.qt.io/qt-5/qcompleter.html#wrapAround-prop',1,'QCompleter']]],
  ['wrapping_59998',['wrapping',['http://doc.qt.io/qt-5/qabstractspinbox.html#wrapping-prop',1,'QAbstractSpinBox::wrapping()'],['http://doc.qt.io/qt-5/qdial.html#wrapping-prop',1,'QDial::wrapping()']]],
  ['writingsystem_59999',['writingSystem',['http://doc.qt.io/qt-5/qfontcombobox.html#writingSystem-prop',1,'QFontComboBox']]]
];
